services:
  subnetx:
    build:
      context: .
      dockerfile: ./docker/subnetx.Dockerfile
    container_name: subnetx_vpn
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    privileged: true
    volumes:
      - .:/app
      - ./certs:/etc/openvpn/certs
      - ./logs:/var/log/openvpn
    ports:
      - "${OPENVPN_PORT}:${OPENVPN_PORT}/udp"
    environment:
      - VPN_NETWORK=${VPN_NETWORK}
      - VPN_NETMASK=${VPN_NETMASK}
      - OPENVPN_PORT=${OPENVPN_PORT}
      - OPENVPN_PROTO=${OPENVPN_PROTO}
      - TUN_DEVICE=${TUN_DEVICE}
      - PUBLIC_IP=${PUBLIC_IP}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - subnetx

  # subnetx-monitor:
  #   build:
  #     context: ./metrics
  #     dockerfile: Dockerfile
  #   container_name: subnetx_monitor
  #   restart: unless-stopped
  #   volumes:
  #     - ./logs:/var/log/openvpn
  #     - ./logs/subnetx:/var/log/subnetx
  #   environment:
  #     - VPN_NETWORK=${VPN_NETWORK}
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "3"
  #   networks:
  #     - subnetx

  duckdns:
    image: linuxserver/duckdns
    container_name: subnetx_vpn_duckdns
    restart: unless-stopped
    environment:
      - SUBDOMAINS=${PUBLIC_IP}
      - TOKEN=${DUCKDNS_TOKEN}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - subnetx

networks:
  subnetx:
    driver: bridge
