version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ./services/api/Dockerfile
    container_name: subnetx_api
    restart: unless-stopped
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    command: ["uvicorn", "services.api.src.main:app", "--host", "0.0.0.0", "--port", "${API_PORT}", "--reload"]
    networks:
      - subnetx
    depends_on:
      postgres:
        condition: service_healthy

  subnetx:
    build:
      context: .
      dockerfile: ./services/vpn/Dockerfile
    container_name: subnetx_vpn
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    privileged: true
    volumes:
      - ./docker/volumes/certs:/etc/openvpn/certs
      - ./docker/volumes/logs:/var/log/openvpn
    ports:
      - ${OPENVPN_PORT}:${OPENVPN_PORT}/${OPENVPN_PROTO}
      - ${VPN_API_PORT}:${VPN_API_PORT}
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - VPN_API_HOST=${VPN_API_HOST}
      - VPN_API_PORT=${VPN_API_PORT}
    networks:
      - subnetx
    depends_on:
      postgres:
        condition: service_healthy

  # duckdns:
  #   image: linuxserver/duckdns
  #   container_name: subnetx_duckdns
  #   restart: unless-stopped
  #   environment:
  #     - SUBDOMAINS=${PUBLIC_IP}
  #     - TOKEN=${DUCKDNS_TOKEN}
  #   networks:
  #     - subnetx

  ui:
    build:
      context: ./services/ui
      dockerfile: Dockerfile
    container_name: subnetx_ui
    volumes:
      - ./services/ui:/app
      - ./docker/volumes/ui_node_modules:/app/node_modules
      - ./docker/volumes/ui_next_cache:/app/.next
      - ./services/ui/scripts:/app/scripts
    ports:
      - "3200:3200"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://subnetx_vpn:${VPN_API_PORT}
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - NEXT_TELEMETRY_DISABLED=1
      - NODE_OPTIONS=--max_old_space_size=4096
    networks:
      - subnetx
    depends_on:
      - subnetx
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: subnetx_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./docker/volumes/postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - subnetx

networks:
  subnetx:
    driver: bridge

volumes:
  ui_node_modules:
  ui_next_cache:
