[tool.black]
# Configuraci贸n para black
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
# Configuraci贸n para isort
profile = "black"
line_length = 88
multi_line_output = 3

[tool.mypy]
# Configuraci贸n para mypy
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
follow_imports = "skip"
ignore_missing_imports = true
show_error_codes = true

[tool.pylint.messages_control]
# Configuraci贸n para pylint
disable = [
    "C0111", # missing-docstring
    "C0103", # invalid-name
    "W0621", # redefined-outer-name
    "R0903", # too-few-public-methods
    "R0913", # too-many-arguments
    "W1203", # logging-fstring-interpolation
    "W0718", # broad-exception-caught
]

[tool.pylint.format]
max-line-length = 88

[tool.pylint.design]
max-args = 6
max-attributes = 12

[tool.flake8]
max-line-length = 88
extend-ignore = "E203"
ignore-docstring-length = True
exclude = [".git", "__pycache__", "build", "dist"]
