[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:api_server]
command=python3 -m vpn.metrics.api.api_server
directory=/app
autostart=true
autorestart=true
startsecs=5
stopwaitsecs=10
stderr_logfile=/var/log/api.err.log
stdout_logfile=/var/log/api.out.log
environment=PYTHONPATH="/app",API_HOST="0.0.0.0",API_PORT="8000"

[program:ping_monitor]
command=python3 -m vpn.metrics.main
directory=/app
autostart=true
autorestart=true
startsecs=5
stopwaitsecs=10
stderr_logfile=/var/log/ping_monitor.err.log
stdout_logfile=/var/log/ping_monitor.out.log
environment=PYTHONPATH="/app"
